import "./globals.css";
import GlobalState from "@/context";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import Loading from "./loading";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Loading />
        <GlobalState>
            {children}
          <ToastContainer />
        </GlobalState>
      </body>
    </html>
  );
}
